aws-solutions/content-localization-on-aws

src/components/Translation.vue
src/views/Analysis.vue
src/views/UploadToAWSS3.vue

Issue #, if available:
closes #17
Description of changes:
Add Translate Parallel Data (ACT) as input for the localization workflow

Add Translate Parallel Data as input to localization workflow

---

.github/workflows/scheduled-workflow.yml

add dispatch to scheduled-workflow

---

.github/workflows/release-workflow.yml

Need build access to delete stack

---

.github/workflows/scheduled-workflow.yml
.github/workflows/test-scheduled-workflow.yml

Don't deploy MIE TestStack for scheduled workflow

Don't deploy MIE TestStack for scheduled workflow

---

.github/workflows/pr-workflow.yml
.github/workflows/scheduled-workflow.yml

The workflow can only be triggered if an authenticated owner of the repo creates the PR.

Add deploy back to PR workflow

---

src/views/UploadToAWSS3.vue

VTT file input is overwritten with Terminology.

---

.github/workflows/scheduled-workflow.yml
test/e2e/conftest.py
test/e2e/requirements.txt
test/e2e/run_e2e.sh
test/e2e/test_app.py

First UI test that can run in the scheduled-workflow
Basic test of minimal settings for subtitles workflow

UI test for Upload View

---

cloudformation/aws-content-analysis-auth.yaml
cloudformation/aws-content-localization-deploy-mie.yaml
cloudformation/aws-content-localization.yaml
deployment/build.sh
package.json
src/components/MediaSummaryBox.vue
src/components/Subtitles.vue
src/components/vue-dropzone.vue
src/main.js
src/views/Analysis.vue
src/views/Collection.vue
src/views/UploadToAWSS3.vue
test/e2e/conftest.py
test/e2e/run_e2e.sh
test/e2e/test_app.py

Fixes #46 
Fixes #114
Merge with aws-media-insights repo
- major: Allow multiple file upload with dropzone
Get source language code from the correct stage configuration
Start of end-to-end ui tests

Merge with latest changes from awslabs/aws-media-insights project

---

.github/workflows/test-ui-standalone.yml
test/e2e/conftest.py
test/e2e/test_app.py

Debug UI test in Actions

---

.github/workflows/test-ui-standalone.yml
test/e2e/test_app.py

Use xpath instead of link text to locate elements

---

test/e2e/test_app.py

maximize browser in headless mode

---

test/e2e/test_workflow_reprocess.py

run in headless mode in automated envs

---

cloudformation/aws-content-analysis-elasticsearch.yaml
cloudformation/aws-content-localization-deploy-mie.yaml
cloudformation/aws-content-localization.yaml
consumer/lambda_handler.py
deployment/requirements.txt
test/e2e/test_app.py
test/e2e/test_workflow_reprocess.py

- Remove the music from the start of the test video as this was causing inconsistent results from Transcribe
- add Service API tag to elasticsearch consumer S3 calls
- change the solution id to S00164

Improve reliability of nightly tests and update solution ID 

---

.github/workflows/pr-workflow.yml
.github/workflows/release-workflow.yml
.gitignore
README.md

#148 
Recent changes in the build script broke the release workflow. This PR fixes the release workflow.

fix release workflow

---

deployment/aws-content-localization-web.yaml

Fix an S3 bucket policy that allows non-secure transport on the base url for the web endpoint

disallow non-secure transport on the base web endpoint

---

CHANGELOG.md
NOTICE
README.md
deployment/aws-content-localization-video-workflow.yaml
source/website/src/components/Translation.vue
source/website/src/views/UploadToAWSS3.vue
test/e2e/conftest.py

Updates for threat modeling, security matrix and documentation reviews.
Add NOTICE
Add CHANGELOG.md
Add Uninstall instructions in README (screenshot to be added later)
Add Updating indexes in README (screenshots to be added later)
Additional stage naming simplifications

Add project documentation

---

source/website/src/components/Subtitles.vue
source/website/src/components/Translation.vue
source/website/src/components/VoerroTagsInput.vue
source/website/src/views/Analysis.vue
source/website/src/views/UploadToAWSS3.vue

fix lint warnings and errors

---

source/website/src/components/Translation.vue
source/website/src/components/VideoPlayer.vue

Alphabetize caption list

---

README.md
deployment/content-localization-on-aws-video-workflow.yaml

Add whitespace before version
Use correct path for IMPLEMENTATION GUIDE operational metrics collection section.

resolve SB review  comments

---

source/website/src/components/Subtitles.vue

fix source language when saving a new or updated custom vocab

---

source/website/src/views/Analysis.vue

get the proxy video file from dataplane bucket instead of the source bucket for the input media

---

test/e2e/conftest.py

#253 
Related to https://github.com/aws-solutions/aws-media-insights-engine/issues/524

enable SSL certificate checks

---

README.md
doc/sigv4_post_sample.py

Closes #265 
Document how to start workflows from the command line and from an s3 trigger.

Add s3 trigger

---

test/e2e/test_app.py

fix xpath to pause button

---

test/e2e/conftest.py

update e2e test to work with the API changes introduced in MIE 4.0.0

---

source/website/src/components/Subtitles.vue

provide option to download SRT

---

deployment/content-localization-on-aws-video-workflow.yaml

Closes #267 
This fix requires MIE 4.0.0, or whatever release includes the following PR:
https://github.com/aws-solutions/aws-media-insights-engine/pull/641

record the workflow state machine ARN in the outputs for the VideoWorkflow

---

source/website/package.json
source/website/src/components/Subtitles.vue
source/website/src/components/Transcript.vue

remove profanity checker due to insufficient support for non-english

---

.github/workflows/pr-workflow.yml
.github/workflows/release-workflow.yml
.github/workflows/scheduled-workflow.yml
.viperlightignore
CHANGELOG.md

These are the changes needed to address issues raised by viperlight.

resolve viperlight issues

---

source/website/src/components/Subtitles.vue
source/website/src/components/Translation.vue
test/e2e/test_workflow_reprocess.py

Store the original workflow id so the subtitles view can get transcribe and caption data from that.

Fix save edits

---

source/website/src/components/Subtitles.vue

specify source language in workflow execution request

---

README.md
source/website/src/components/Subtitles.vue
source/website/src/views/UploadToAWSS3.vue

Issue #, if available:
Closes https://github.com/aws-solutions/aws-media-insights-content-localization/issues/116
Description of changes:
Depends on aws-solutions/aws-media-insights-engine#599.

Add support for custom language models in transcribe 

---

source/website/src/components/MediaSummaryBox.vue

Trim mediasummary

---

source/consumer/lambda_handler.py
source/website/src/components/Celebrities.vue
source/website/src/components/ComprehendEntities.vue
source/website/src/components/ComprehendKeyPhrases.vue
source/website/src/components/ContentModeration.vue
source/website/src/components/FaceDetection.vue
source/website/src/components/LabelObjects.vue
source/website/src/components/ShotDetection.vue
source/website/src/components/TechnicalCues.vue
source/website/src/components/TextDetection.vue

Fix opensearch throttling and add modal to show api reqs

---

source/website/src/views/UploadToAWSS3.vue

Closes #305
Exclude 'auto' from target languages when user specified 'auto' as the source language

Exclude 'auto' from target languages 

---

source/website/src/components/Subtitles.vue

Use correct field name when loading custom vocab DisplayAs column.

---

test/e2e/run_e2e.sh
test/e2e/test_app.py

save screenshot to help troubleshoot nightswatch error

---

.github/workflows/pr-workflow.yml
CHANGELOG.md
deployment/content-localization-on-aws-use-existing-mie-stack.yaml
deployment/content-localization-on-aws.yaml
source/consumer/requirements.txt
test/e2e/requirements.txt

- AppRegistry integration
- Updated requests-aws4auth package to v1.2.2

AppRegistry integration

---

CHANGELOG.md
NOTICE
deployment/content-localization-on-aws-opensearch.yaml
deployment/content-localization-on-aws-web.yaml
deployment/content-localization-on-aws.yaml
source/website/package-lock.json
source/website/package.json
source/website/src/components/Subtitles.vue
source/website/src/components/Translation.vue
source/website/src/main.js
source/website/src/router.js
source/website/src/store/index.js
source/website/src/views/UploadToAWSS3.vue
source/website/vue.config.js
test/e2e/requirements.txt

* Added resource dependency on OpensearchServiceDomain
* Upgraded to Media Insights on AWS v5.1.6
* Enabled versioning on website bucket
* Upgraded vulnerable packages 
* Replaced some bootstrap-vue code that was incompatible with Vue 2 to 3 migration build

Update to v2.1.3

---

CHANGELOG.md
deployment/content-localization-on-aws.yaml
source/website/package-lock.json
source/website/package.json
test/e2e/requirements.txt
test/unit/requirements.txt

* Updated `Media Insights on AWS` version to v5.1.7
* Upgraded vulnerable packages

Update to v2.1.5

---

CHANGELOG.md
NOTICE
SECURITY.md
deployment/content-localization-on-aws.yaml
source/website/package-lock.json
source/website/package.json

Security
* Upgraded vulnerable packages

Release v2.1.7

---

CHANGELOG.md
source/website/package-lock.json
source/website/package.json

- Upgraded vulnerable packages

Update to v2.1.8

---

CHANGELOG.md
source/website/package-lock.json
source/website/package.json

- Upgraded vulnerable packages

Release v2.1.9

---

CHANGELOG.md
source/website/package-lock.json
source/website/package.json

- Upgraded vulnerable packages

Release v2.1.10
